---
name: Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Yamllint
        run: pip install -y yamllint
      - name: Lint Recipes
        run: "yamllint *.yml"
