name: WhatsApp Message

on: [push]

jobs:
  message:
    runs-on: ubuntu-latest

    steps:
    - name: Send WhatsApp Message
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_WHATSAPP_FROM: ${{ secrets.TWILIO_WHATSAPP_FROM }}
        TWILIO_WHATSAPP_TO: ${{ secrets.TWILIO_WHATSAPP_TO }}
      run: |
        curl -X POST "https://api.twilio.com/2010-04-01/Accounts/$TWILIO_ACCOUNT_SID/Messages.json" \
        --data-urlencode "From=$TWILIO_WHATSAPP_FROM" \
        --data-urlencode "To=$TWILIO_WHATSAPP_TO" \
        --data-urlencode "Body=Hello, this is a message from GitHub Actions!" \
        -u $TWILIO_ACCOUNT_SID:$TWILIO_AUTH_TOKEN
